---
title: "Optimal play of the dice game pig"
author: "Luis Ramos Grados, Carlos Alberto Espinoza Mansilla"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción
Nuestro objetivo con este proyecto es encontrar una forma óptima de jugar(y ganar) el "play of the dice game pig" para esto es necesario conocer las reglas del juego:

El juego inicia

* El primer jugador tira el dado
* Si saca 1 el puntaje acumulado durante su turno se vuelve cero y su turno termina 
* Si saca de 2 a 6 el resultado se suma al puntaje de ese turno
* Ahora el jugador decide si vuelve a tirar el dado o terminar su turno
* Si el jugador termina su turno el puntaje acumulado durante su turno se suma al puntaje del jugador
* Si el jugador decide volver a lanzar se repetira el proceso hasta que decida terminar su turno o saque 1
*El juego termina cuando un jugador logra acumular 100 o mas puntos.

A pesar de que este juego tiene muchas mas variaciones y puede jugarse de 2 a 10 jugadores aqui tomaremos la forma estandar del juego que es la ya descrita y jugada por 2 personas con un dado de 6 lados justo. Trataremos de maximizar nuestrar probabilidades de ganar usando nuestro conocimientos sobre probabilidades y luego computaremos los algoritmos que sean necesarios para resolver el problema con las herramientas que nos da R.


## Estado del arte

1. Practical Play of the Dice Game Pig por Todd W. Neller, Clifton G.M. Presser: Siendo conciente de lo complicado del resultado "óptimo" para que un humano lo aplique en un entorno casual, busca una forma que sin ser la mas óptima resulta mas conveniente para jugar de forma optimo de modo casual.

2. Pig (Pig-out): Análisis de una de las variaciones del juego original esta vez con 2 dados.

## Diseño del experimento

Primero vamos a definir de que cosas depende la probabilidad de ganar de nuestro jugador:
Para un turno cualquiera de nuestro jugador la posibilidad de ganar va a depender de cuantos puntos tengemos (i), de cuantos puntos tiene nuestro oponente (j), de cuantos puntos tenemos acumulados en nuestro turno (k) y de decidir si volver a lanzar el dado o terminar el turno dependiendo de cual me da mas posibilidades de ganar, entonces definimos nuestras posibilidades de ganar como:

$P_{i,j,k}=max(P_{i,j,k,lanzar},P_{i,j,k,terminar})$ 

Donde $P_{i,j,k}$ es la posibilidad de ganar total, $P_{i,j,k,lanzar}$ es la posibilidad de ganar lanzando de nuevo el dado y $P_{i,j,k,terminar}$ es la posibilidad de ganar terminando ese turno.

Ahora si consideramos la situación en la que $i+k\geq 100$ entonces $P_{i,j,k}=1$ porque le basta al jugador con terminar allí su turno para ganar, también podemos establecer limites para i,j,k:

$0\leq i < 100$ , $0\leq j < 100$ y $0\leq k < 100-i$

ahora la probabilidad de ganar terminando nuestro turno va a ser igual a la probabilidad de que nuestro oponente no gane:

$P_{i,j,k,terminar}=1-P_{j,i,0}$ 

Mientras que la probabilida de ganar volviendo a lanzar el dado es la suma de las probabilidades de ganar obteniendo (1,2,3,4,5,6) multiplicado por la posibilidad de que se de dicho resultado:

$P_{i,j,k,lanzar}=[\frac{1}{6}P_{i,j,k+1}+\frac{1}{6}P_{i,j,k+2}+\frac{1}{6}P_{i,j,k+3}+\frac{1}{6}P_{i,j,k+4}+\frac{1}{6}P_{i,j,k+5}+\frac{1}{6}P_{i,j,k+6}]$

pero $P_{i,j,k+1}$ significa que todo el k acumulado se reduce a 0 y termina tu turno por lo $P_{i,j,k+1} = 1-P_{j,i,0}$ ahora:

$P_{i,j,k,lanzar}=\frac{1}{6}[(1-P_{j,i,0})+P_{i,j,k+2}+P_{i,j,k+3}+P_{i,j,k+4}+P_{i,j,k+5}+P_{i,j,k+6}]$

Bueno, ya hemos contruido un modelo matematico para calcular la probabilidad óptima de ganar solo queda resolver.

## Experimentos y resultados

## Discusión

## Conclusiones

## Bibliografía o Referencias

[1] http://cs.gettysburg.edu/~tneller/papers/umap10.pdf Practical Play of the Dice Game Pig por Todd W. Neller

[2] http://www.durangobill.com/Pig.html Pig (Pig-out)

[3] https://people.eecs.berkeley.edu/~pabbeel/cs287-fa12/slides/mdps-exact-methods.pdf
